development:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  minerthreads: 1
  genesis_block: config/genesis/dev_genesis.json
  datadir: /tmp/embark
  mine_when_needed: true
  mine_periodically: false
  max_peers: 0
  gas_limit: 3000000
  gas_price: 100000000000
  console: false
  whisper: true
  account:
    init: true
    password: config/password
staging:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 0
  max_peers: 4
  console: true
  account:
    init: false
    address:
production:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 1
  max_peers: 4
  console: true
  account:
    init: false
    address:
