development:
  Store:
    deploy: false
  Market:
    deploy: false
  Order:
    deploy: false
  Forum:
    deploy: false
  aliasable:
    deploy: false
  owned:
    deploy: false
  forumable:
    deploy: false
  audible:
    deploy: false
  OpenStore:
    onDeploy:
      - OpenStore.set('CMC:TETH:USD', new BigNumber('2100000000000'));
      - OpenStore.set('CMC:TETH:EUR', new BigNumber('2200000000000'));
      - OpenStore.set('CMC:TETH:CNY', new BigNumber('2300000000000'));
      - OpenStore.set('CMC:TETH:CAD', new BigNumber('2400000000000'));
      - OpenStore.set('CMC:TETH:RUB', new BigNumber('2500000000000'));
      - OpenStore.set('CMC:TETH:BTC', new BigNumber('2600000000000'));
testnet:
  Store:
    deploy: false
  Market:
    deploy: false
  Order:
    deploy: false
  Forum:
    deploy: false
  aliasable:
    deploy: false
  owned:
    deploy: false
  forumable:
    deploy: false
  audible:
    deploy: false
  OpenStore:
    onDeploy:
      - OpenStore.set('CMC:TETH:USD', new BigNumber('2100000000000'));
      - OpenStore.set('CMC:TETH:EUR', new BigNumber('2200000000000'));
      - OpenStore.set('CMC:TETH:CNY', new BigNumber('2300000000000'));
      - OpenStore.set('CMC:TETH:CAD', new BigNumber('2400000000000'));
      - OpenStore.set('CMC:TETH:RUB', new BigNumber('2500000000000'));
      - OpenStore.set('CMC:TETH:BTC', new BigNumber('2600000000000'));
production:
  Store:
    deploy: false
  Market:
    deploy: false
  Order:
    deploy: false
  Forum:
    deploy: false
  aliasable:
    deploy: false
  owned:
    deploy: false
  forumable:
    deploy: false
  audible:
    deploy: false
  OpenStore:
    address: 0xaf527686227cc508ead0d69c7f8a98f76b63e191
